;;; tests/advanced-facet-tests.el --- Advanced tests for native faceting -*- lexical-binding: t; -*-

(require 'test-helper)
(require 'drake)
(require 'drake-gnuplot)
(require 'drake-rust)
(require 'drake-svg)

;;; Faceting with different plot types

(ert-deftest drake-facet-with-line-plots ()
  "Test faceting with line plots."
  (let* ((data '(:x [1 2 3 1 2 3]
                 :y [10 20 30 15 25 35]
                 :category ["A" "A" "A" "B" "B" "B"]))
         (fplot (drake-facet :data data :col :category
                            :plot-fn #'drake-plot-line
                            :args '(:x :x :y :y)
                            :backend 'svg)))
    (should (drake-facet-plot-p fplot))
    (should (= (drake-facet-plot-cols fplot) 2))
    (should (drake-facet-plot-image fplot))))

(ert-deftest drake-facet-with-bar-plots ()
  "Test faceting with bar plots."
  (let* ((data '(:x ["X" "Y" "X" "Y"]
                 :y [10 20 15 25]
                 :category ["A" "A" "B" "B"]))
         (fplot (drake-facet :data data :col :category
                            :plot-fn #'drake-plot-bar
                            :args '(:x :x :y :y)
                            :backend 'svg)))
    (should (drake-facet-plot-p fplot))
    (should (= (drake-facet-plot-cols fplot) 2))
    (should (drake-facet-plot-image fplot))))

(ert-deftest drake-facet-with-violin-plots ()
  "Test faceting with violin plots."
  (let* ((data '(:x ["G1" "G1" "G1" "G2" "G2" "G2"]
                 :y [12 15 18 14 16 22]
                 :category ["A" "A" "A" "B" "B" "B"]))
         (fplot (drake-facet :data data :col :category
                            :plot-fn #'drake-plot-violin
                            :args '(:x :x :y :y)
                            :backend 'svg)))
    (should (drake-facet-plot-p fplot))
    (should (= (drake-facet-plot-cols fplot) 2))
    (should (drake-facet-plot-image fplot))))

;;; Faceting with both row and column

(ert-deftest drake-facet-2x2-grid ()
  "Test 2x2 facet grid."
  (let* ((data '(:x [1 2 1 2 1 2 1 2]
                 :y [10 20 30 40 50 60 70 80]
                 :row-var ["R1" "R1" "R1" "R1" "R2" "R2" "R2" "R2"]
                 :col-var ["C1" "C1" "C2" "C2" "C1" "C1" "C2" "C2"]))
         (fplot (drake-facet :data data
                            :row :row-var
                            :col :col-var
                            :plot-fn #'drake-plot-scatter
                            :args '(:x :x :y :y)
                            :backend 'svg)))
    (should (drake-facet-plot-p fplot))
    (should (= (drake-facet-plot-rows fplot) 2))
    (should (= (drake-facet-plot-cols fplot) 2))
    (should (= (length (drake-facet-plot-grid fplot)) 2))
    (should (= (length (car (drake-facet-plot-grid fplot))) 2))
    (should (drake-facet-plot-image fplot))))

(ert-deftest drake-facet-3x1-grid ()
  "Test 3x1 facet grid (3 columns)."
  (let* ((data '(:x [1 2 3 1 2 3 1 2 3]
                 :y [10 20 30 15 25 35 20 30 40]
                 :group ["A" "A" "A" "B" "B" "B" "C" "C" "C"]))
         (fplot (drake-facet :data data
                            :col :group
                            :plot-fn #'drake-plot-scatter
                            :args '(:x :x :y :y)
                            :backend 'svg)))
    (should (drake-facet-plot-p fplot))
    (should (= (drake-facet-plot-rows fplot) 1))
    (should (= (drake-facet-plot-cols fplot) 3))
    (should (drake-facet-plot-image fplot))))

;;; Faceting with title

(ert-deftest drake-facet-with-title ()
  "Test faceting with overall title."
  (let* ((data '(:x [1 2 3 4] :y [10 20 10 20] :category ["A" "A" "B" "B"]))
         (fplot (drake-facet :data data :col :category
                            :plot-fn #'drake-plot-scatter
                            :args '(:x :x :y :y)
                            :title "Overall Facet Title"
                            :backend 'svg)))
    (should (drake-facet-plot-p fplot))
    (should (string= (drake-facet-plot-title fplot) "Overall Facet Title"))
    (should (drake-facet-plot-image fplot))))

;;; Backend-specific tests

(ert-deftest drake-facet-gnuplot-multiplot ()
  "Test gnuplot native multiplot rendering."
  (skip-unless (executable-find "gnuplot"))
  (let* ((data '(:x [1 2 3 1 2 3 1 2 3]
                 :y [10 20 30 15 25 35 20 30 40]
                 :group ["A" "A" "A" "B" "B" "B" "C" "C" "C"]))
         (fplot (drake-facet :data data
                            :col :group
                            :plot-fn #'drake-plot-line
                            :args '(:x :x :y :y)
                            :backend 'gnuplot)))
    (should (drake-facet-plot-p fplot))
    (should (= (drake-facet-plot-cols fplot) 3))
    (should (drake-facet-plot-image fplot))
    ;; Verify SVG was generated by gnuplot
    (should (drake-facet-plot-svg-xml fplot))
    (should (string-match-p "svg" (drake-facet-plot-svg-xml fplot)))))

(ert-deftest drake-facet-rust-grid-rendering ()
  "Test Rust backend native grid rendering."
  (let* ((data '(:x [1 2 1 2]
                 :y [10 20 30 40]
                 :row-var ["R1" "R1" "R2" "R2"]
                 :col-var ["C1" "C2" "C1" "C2"]))
         (fplot (drake-facet :data data
                            :row :row-var
                            :col :col-var
                            :plot-fn #'drake-plot-scatter
                            :args '(:x :x :y :y)
                            :backend 'rust)))
    (should (drake-facet-plot-p fplot))
    (should (= (drake-facet-plot-rows fplot) 2))
    (should (= (drake-facet-plot-cols fplot) 2))
    (should (drake-facet-plot-image fplot))
    (should (drake-facet-plot-svg-xml fplot))))

(provide 'advanced-facet-tests)
